# Generated by Django 4.0.5 on 2022-06-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=30)),
                ('zipcode', models.SmallIntegerField(default=None)),
                ('neighborhood', models.CharField(default='', max_length=200)),
                ('lat', models.FloatField(default=None)),
                ('long', models.FloatField(default=None)),
                ('property_type', models.CharField(default='', max_length=30)),
                ('septic_tank', models.BooleanField(default=False)),
                ('garage_spaces', models.SmallIntegerField(default=None)),
                ('purchase_price', models.IntegerField(default=None)),
                ('rehab_costs', models.IntegerField(default=None)),
                ('down_payment', models.IntegerField(default=None)),
                ('loan_amount', models.IntegerField(default=None)),
                ('closing_costs', models.IntegerField(default=None)),
                ('equity_required', models.IntegerField(default=None)),
                ('mortgage', models.SmallIntegerField(default=None)),
                ('mortgate_rate', models.FloatField(default=None)),
                ('rent', models.SmallIntegerField(default=None)),
                ('rent_after_vacancy', models.SmallIntegerField(default=None)),
                ('effective_gross_income', models.SmallIntegerField(default=None)),
                ('net_cash_flow', models.SmallIntegerField(default=None)),
                ('property_tax', models.SmallIntegerField(default=None)),
                ('hoa', models.SmallIntegerField(default=None)),
                ('property_management', models.SmallIntegerField(default=None)),
                ('home_insurance', models.SmallIntegerField(default=None)),
                ('monthly_repairs', models.SmallIntegerField(default=None)),
                ('monthly_capex', models.SmallIntegerField(default=None)),
                ('cap_rate', models.FloatField(default=None)),
                ('cash_on_cash', models.FloatField(default=None)),
            ],
        ),
    ]
