# Generated by Django 4.0.5 on 2022-06-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='id',
        ),
        migrations.AddField(
            model_name='properties',
            name='address_line_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='properties',
            name='address_line_2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='properties',
            name='full_address',
            field=models.CharField(default='', max_length=300, primary_key=True, serialize=False),
        ),
    ]
