# Generated by Django 4.0.5 on 2022-06-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_properties_id_properties_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='mortgate_rate',
            new_name='mortgage_rate',
        ),
    ]
