# Generated by Django 4.0.5 on 2022-09-28 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_properties_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='mortgage',
            new_name='mortgage_payment',
        ),
        migrations.AddField(
            model_name='properties',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_contingent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_foreclosure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_new_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_new_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_price_reduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_subdivision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='last_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='properties',
            name='net_operating_income',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_sub_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='properties',
            name='total_monthly_expenses',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='properties',
            name='us_real_estate_api_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='year_built',
            field=models.SmallIntegerField(default=None),
        ),
    ]
